replicaCount: 1

image:
  repository: hk00d/my-weatherapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080   # optional, can be auto-assigned

resources: {}