apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-weatherapp.fullname" . }}
  labels:
    app: {{ include "my-weatherapp.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "my-weatherapp.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default 30080 }}